<a href="https://colab.research.google.com/github/hamzaadw/Data-analysis-Practice/blob/main/Covid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

d = pd.read_csv("covid_19_india.csv")
d.head()

d["Date"] = pd.to_datetime(d["Date"])
d.columns=d.columns.str.replace("/","_").str.lower()
d.sort_values(by=["state_unionterritory", "date"])
d.head(10)

,sno,date,time,state_unionterritory,confirmedindiannational,confirmedforeignnational,cured,deaths,confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
5,6,2020-02-04,6:00 PM,Kerala,3,0,0,0,3
6,7,2020-02-05,6:00 PM,Kerala,3,0,0,0,3
7,8,2020-02-06,6:00 PM,Kerala,3,0,0,0,3
8,9,2020-02-07,6:00 PM,Kerala,3,0,0,0,3
9,10,2020-02-08,6:00 PM,Kerala,3,0,0,0,3

In [ ]:
# Filter the dataset to show only rows where daily confirmed cases > 10,000.

filtered = d[d["confirmed"] > 10000]
print(filtered)

         sno       date     time state_unionterritory confirmedindiannational  \
1496    1497 2020-05-01  5:00 PM          Maharashtra                       -
1528    1529 2020-05-02  5:00 PM          Maharashtra                       -
1560    1561 2020-05-03  5:00 PM          Maharashtra                       -
1592    1593 2020-05-04  5:00 PM          Maharashtra                       -
1624    1625 2020-05-05  5:00 PM          Maharashtra                       -
...      ...        ...      ...                  ...                     ...
18105  18106 2021-08-11  8:00 AM            Telangana                       -
18106  18107 2021-08-11  8:00 AM              Tripura                       -
18107  18108 2021-08-11  8:00 AM          Uttarakhand                       -
18108  18109 2021-08-11  8:00 AM        Uttar Pradesh                       -
18109  18110 2021-08-11  8:00 AM          West Bengal                       -

      confirmedforeignnational    cured  deaths  confirmed
1496                         -     1773     459      10498
1528                         -     1879     485      11506
1560                         -     2000     521      12296
1592                         -     2115     548      12974
1624                         -     2465     583      14541
...                        ...      ...     ...        ...
18105                        -   638410    3831     650353
18106                        -    77811     773      80660
18107                        -   334650    7368     342462
18108                        -  1685492   22775    1708812
18109                        -  1506532   18252    1534999

[12015 rows x 9 columns]

In [ ]:
# Group the data by state_unionterritory and compute:

# Total confirmed cases

# Total deaths

# Maximum recovered cases in a single day





d["daily_recovered"] = d.groupby("state_unionterritory")["cured"].diff()



daily_recovered_stats = d.groupby("state_unionterritory").agg(
    total_confirmed=("confirmed", "sum"),
    total_deaths=("deaths", "sum"),
    max_daily_recovered=("daily_recovered", "max")
).sort_values(by="total_confirmed", ascending=False)

print(daily_recovered_stats)

0          NaN
1          0.0
2          0.0
3          0.0
4          0.0
         ...
18105    621.0
18106    210.0
18107     41.0
18108     43.0
18109    724.0
Name: daily_recovered, Length: 18110, dtype: float64
                                          total_confirmed  total_deaths  \
state_unionterritory
Maharashtra                                    1121491467      23737432
Karnataka                                       485970693       6053762
Kerala                                          458906023       1888177
Tamil Nadu                                      431928644       5916658
Andhra Pradesh                                  392432753       2939367
Uttar Pradesh                                   312625843       4143450
Delhi                                           287227765       4943294
West Bengal                                     263107876       3846989
Chhattisgarh                                    163776262       2063920
Rajasthan                                       162369656       1473089
Odisha                                          160130533        790814
Gujarat                                         143420082       2219448
Madhya Pradesh                                  135625265       1777752
Haryana                                         134347285       1502799
Bihar                                           132231166       1093466
Punjab                                           99949702       2785594
Assam                                            99837011        638323
Telengana                                        69990668        400427
Jharkhand                                        62111994        748641
Telangana                                        60571979        349648
Jammu and Kashmir                                58117726        839694
Uttarakhand                                      53140414        986001
Himachal Pradesh                                 30033289        491348
Goa                                              28240159        447801
Puducherry                                       20065891        312155
Tripura                                          14050250        150342
Manipur                                          12617943        173056
Chandigarh                                       10858627        147694
Meghalaya                                         7355969        101950
Arunachal Pradesh                                 7176907         26799
Maharashtra***                                    6229596        130753
Nagaland                                          5041742         58460
Ladakh                                            4054293         45804
Sikkim                                            3186799         53150
Mizoram                                           2984732          9791
Karanataka                                        2885238         36197
Dadra and Nagar Haveli and Daman and Diu          1938632          1014
Andaman and Nicobar Islands                       1938498         27136
Bihar****                                         1430909         18881
Lakshadweep                                        915784          3908
Madhya Pradesh***                                  791656         10506
Cases being reassigned to states                   345565             0
Himanchal Pradesh                                  204516          3507
Dadra and Nagar Haveli                              20722             8
Unassigned                                            161             0
Daman & Diu                                             2             0

                                          max_daily_recovered
state_unionterritory
Maharashtra                                           82266.0
Karnataka                                             61766.0
Kerala                                                99651.0
Tamil Nadu                                            33646.0
Andhra Pradesh                                        24819.0
Uttar Pradesh                                         40852.0
Delhi                                                 29287.0
West Bengal                                           19670.0
Chhattisgarh                                          18746.0
Rajasthan                                             29459.0
Odisha                                                23467.0
Gujarat                                               15365.0
Madhya Pradesh                                        14562.0
Haryana                                               16192.0
Bihar                                                 15800.0
Punjab                                                 9059.0
Assam                                                  6266.0
Telengana                                              6542.0
Jharkhand                                              8331.0
Telangana                                              9122.0
Jammu and Kashmir                                      4956.0
Uttarakhand                                            8780.0
Himachal Pradesh                                       5017.0
Goa                                                    4008.0
Puducherry                                             2017.0
Tripura                                                1066.0
Manipur                                                4083.0
Chandigarh                                              963.0
Meghalaya                                               977.0
Arunachal Pradesh                                       517.0
Maharashtra***                                            NaN
Nagaland                                                966.0
Ladakh                                                  346.0
Sikkim                                                  420.0
Mizoram                                                 953.0
Karanataka                                                NaN
Dadra and Nagar Haveli and Daman and Diu                318.0
Andaman and Nicobar Islands                             148.0
Bihar****                                                 0.0
Lakshadweep                                             352.0
Madhya Pradesh***                                         NaN
Cases being reassigned to states                          0.0
Himanchal Pradesh                                         NaN
Dadra and Nagar Haveli                                  170.0
Unassigned                                                0.0
Daman & Diu                                               NaN

In [ ]:
# Add a new column death_rate = total_deaths / total_confirmed

d["death_rate"] = d["deaths"] / d['confirmed'] *100
d

,sno,date,time,state_unionterritory,confirmedindiannational,confirmedforeignnational,cured,deaths,confirmed,daily_recovered,death_rate
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1,NaN,0.000000
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1,0.0,0.000000
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2,0.0,0.000000
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3,0.0,0.000000
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
18105,18106,2021-08-11,8:00 AM,Telangana,-,-,638410,3831,650353,621.0,0.589065
18106,18107,2021-08-11,8:00 AM,Tripura,-,-,77811,773,80660,210.0,0.958344
18107,18108,2021-08-11,8:00 AM,Uttarakhand,-,-,334650,7368,342462,41.0,2.151480
18108,18109,2021-08-11,8:00 AM,Uttar Pradesh,-,-,1685492,22775,1708812,43.0,1.332797
18109,18110,2021-08-11,8:00 AM,West Bengal,-,-,1506532,18252,1534999,724.0,1.189056

In [ ]:
# Identify the state with the highest death rate.

death_rate_by_state = d.groupby("state_unionterritory").agg(
    total_deaths=("deaths", "sum"),
    total_confirmed=("confirmed", "sum")
)
# print(death_rate_by_state)

death_rate_by_state["death_rate"] = (death_rate_by_state["total_deaths"] / death_rate_by_state["total_confirmed"]) * 100

# Sort to find the highest
highest_death_rate = death_rate_by_state.sort_values(by="death_rate", ascending=False)

print(highest_death_rate.head(1))  # State with highest death rate

                      total_deaths  total_confirmed  death_rate
state_unionterritory
Punjab                     2785594         99949702    2.786996

In [ ]:
# Create a column is_high_risk, set to True if the death rate > 2%, else False.
death_rate_by_state["is_high_risk"] = death_rate_by_state["death_rate"] > 2
print(death_rate_by_state)

                                          total_deaths  total_confirmed  \
state_unionterritory
Andaman and Nicobar Islands                      27136          1938498
Andhra Pradesh                                 2939367        392432753
Arunachal Pradesh                                26799          7176907
Assam                                           638323         99837011
Bihar                                          1093466        132231166
Bihar****                                        18881          1430909
Cases being reassigned to states                     0           345565
Chandigarh                                      147694         10858627
Chhattisgarh                                   2063920        163776262
Dadra and Nagar Haveli                               8            20722
Dadra and Nagar Haveli and Daman and Diu          1014          1938632
Daman & Diu                                          0                2
Delhi                                          4943294        287227765
Goa                                             447801         28240159
Gujarat                                        2219448        143420082
Haryana                                        1502799        134347285
Himachal Pradesh                                491348         30033289
Himanchal Pradesh                                 3507           204516
Jammu and Kashmir                               839694         58117726
Jharkhand                                       748641         62111994
Karanataka                                       36197          2885238
Karnataka                                      6053762        485970693
Kerala                                         1888177        458906023
Ladakh                                           45804          4054293
Lakshadweep                                       3908           915784
Madhya Pradesh                                 1777752        135625265
Madhya Pradesh***                                10506           791656
Maharashtra                                   23737432       1121491467
Maharashtra***                                  130753          6229596
Manipur                                         173056         12617943
Meghalaya                                       101950          7355969
Mizoram                                           9791          2984732
Nagaland                                         58460          5041742
Odisha                                          790814        160130533
Puducherry                                      312155         20065891
Punjab                                         2785594         99949702
Rajasthan                                      1473089        162369656
Sikkim                                           53150          3186799
Tamil Nadu                                     5916658        431928644
Telangana                                       349648         60571979
Telengana                                       400427         69990668
Tripura                                         150342         14050250
Unassigned                                           0              161
Uttar Pradesh                                  4143450        312625843
Uttarakhand                                     986001         53140414
West Bengal                                    3846989        263107876

                                          death_rate  is_high_risk
state_unionterritory
Andaman and Nicobar Islands                 1.399847         False
Andhra Pradesh                              0.749012         False
Arunachal Pradesh                           0.373406         False
Assam                                       0.639365         False
Bihar                                       0.826935         False
Bihar****                                   1.319511         False
Cases being reassigned to states            0.000000         False
Chandigarh                                  1.360154         False
Chhattisgarh                                1.260207         False
Dadra and Nagar Haveli                      0.038606         False
Dadra and Nagar Haveli and Daman and Diu    0.052305         False
Daman & Diu                                 0.000000         False
Delhi                                       1.721036         False
Goa                                         1.585689         False
Gujarat                                     1.547516         False
Haryana                                     1.118593         False
Himachal Pradesh                            1.636011         False
Himanchal Pradesh                           1.714780         False
Jammu and Kashmir                           1.444816         False
Jharkhand                                   1.205308         False
Karanataka                                  1.254559         False
Karnataka                                   1.245705         False
Kerala                                      0.411452         False
Ladakh                                      1.129765         False
Lakshadweep                                 0.426738         False
Madhya Pradesh                              1.310782         False
Madhya Pradesh***                           1.327092         False
Maharashtra                                 2.116595          True
Maharashtra***                              2.098900          True
Manipur                                     1.371507         False
Meghalaya                                   1.385949         False
Mizoram                                     0.328036         False
Nagaland                                    1.159520         False
Odisha                                      0.493856         False
Puducherry                                  1.555650         False
Punjab                                      2.786996          True
Rajasthan                                   0.907244         False
Sikkim                                      1.667818         False
Tamil Nadu                                  1.369823         False
Telangana                                   0.577244         False
Telengana                                   0.572115         False
Tripura                                     1.070031         False
Unassigned                                  0.000000         False
Uttar Pradesh                               1.325370         False
Uttarakhand                                 1.855464         False
West Bengal                                 1.462134         False

In [ ]:
# 🔢 Top 5 states with the highest confirmed cases?

top_5_states = d.groupby("state_unionterritory").agg(
    total_confirmed=("confirmed", "sum")
).sort_values(by="total_confirmed", ascending=False)

print(top_5_states.head(5))

                      total_confirmed
state_unionterritory
Maharashtra                1121491467
Karnataka                   485970693
Kerala                      458906023
Tamil Nadu                  431928644
Andhra Pradesh              392432753

In [ ]:
# 🏥 Which state had the best recovery rate (max recovery / confirmed)?

Best_cured_state  = d.groupby("state_unionterritory").agg(
    total_confirmed=("confirmed", "sum"),
    total_cured=("cured", "sum"))
Best_cured_state["recovery_rate"] = Best_cured_state["total_cured"] / Best_cured_state["total_confirmed"]
Best_cured_state.sort_values(by="recovery_rate", ascending=False)
Best_cured_state.head(1)

                             total_confirmed  total_cured  recovery_rate
state_unionterritory
Andaman and Nicobar Islands          1938498      1848286       0.953463

In [ ]:
# ⚖️ Are there more high-risk or low-risk states based on death rate?

death_rate_state = d.groupby("state_unionterritory").agg(
    total_deaths=("deaths", "sum"),
    total_confirmed=("confirmed", "sum")
)

# Compute death rate %
death_rate_state["death_rate"] = (death_rate_state["total_deaths"] / death_rate_state["total_confirmed"]) * 100

death_rate_state

death_rate_state["risk_level"] = death_rate_state["death_rate"].apply(
    lambda x: "High Risk" if x >= 2 else "Low Risk"
)

death_rate_state

,total_deaths,total_confirmed,death_rate,risk_level
state_unionterritory,,,,
Andaman and Nicobar Islands,27136,1938498,1.399847,Low Risk
Andhra Pradesh,2939367,392432753,0.749012,Low Risk
Arunachal Pradesh,26799,7176907,0.373406,Low Risk
Assam,638323,99837011,0.639365,Low Risk
Bihar,1093466,132231166,0.826935,Low Risk
Bihar****,18881,1430909,1.319511,Low Risk
Cases being reassigned to states,0,345565,0.000000,Low Risk
Chandigarh,147694,10858627,1.360154,Low Risk
Chhattisgarh,2063920,163776262,1.260207,Low Risk
Dadra and Nagar Haveli,8,20722,0.038606,Low Risk
Dadra and Nagar Haveli and Daman and Diu,1014,1938632,0.052305,Low Risk
Daman & Diu,0,2,0.000000,Low Risk
Delhi,4943294,287227765,1.721036,Low Risk
Goa,447801,28240159,1.585689,Low Risk
Gujarat,2219448,143420082,1.547516,Low Risk
Haryana,1502799,134347285,1.118593,Low Risk
Himachal Pradesh,491348,30033289,1.636011,Low Risk
Himanchal Pradesh,3507,204516,1.714780,Low Risk
Jammu and Kashmir,839694,58117726,1.444816,Low Risk
Jharkhand,748641,62111994,1.205308,Low Risk
Karanataka,36197,2885238,1.254559,Low Risk
Karnataka,6053762,485970693,1.245705,Low Risk
Kerala,1888177,458906023,0.411452,Low Risk
Ladakh,45804,4054293,1.129765,Low Risk
Lakshadweep,3908,915784,0.426738,Low Risk
Madhya Pradesh,1777752,135625265,1.310782,Low Risk
Madhya Pradesh***,10506,791656,1.327092,Low Risk
Maharashtra,23737432,1121491467,2.116595,High Risk
Maharashtra***,130753,6229596,2.098900,High Risk
Manipur,173056,12617943,1.371507,Low Risk
Meghalaya,101950,7355969,1.385949,Low Risk
Mizoram,9791,2984732,0.328036,Low Risk
Nagaland,58460,5041742,1.159520,Low Risk
Odisha,790814,160130533,0.493856,Low Risk
Puducherry,312155,20065891,1.555650,Low Risk
Punjab,2785594,99949702,2.786996,High Risk
Rajasthan,1473089,162369656,0.907244,Low Risk
Sikkim,53150,3186799,1.667818,Low Risk
Tamil Nadu,5916658,431928644,1.369823,Low Risk
Telangana,349648,60571979,0.577244,Low Risk
Telengana,400427,69990668,0.572115,Low Risk
Tripura,150342,14050250,1.070031,Low Risk
Unassigned,0,161,0.000000,Low Risk
Uttar Pradesh,4143450,312625843,1.325370,Low Risk
Uttarakhand,986001,53140414,1.855464,Low Risk
West Bengal,3846989,263107876,1.462134,Low Risk